name: Run kselftest subsystem tests

on:
  push:
    branches:
      - master
    paths:
      - "api/**"
      - "transformer/**"
      - "parser/**"
      - ".github/workflows/**"
      - "runner.sh"

jobs:
  kselftest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [vm, tmpfs, capabilities]

    steps:
      - uses: actions/checkout@v4

      - name: Install all dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev libmnl-dev bison flex libhugetlbfs-dev coccinelle python3 python3-pip \
                                  libaio-dev libcap-dev libcap-ng-dev libelf-dev libfuse-dev libgcc-s1 libhugetlbfs-dev \
                                  libmnl-dev libmount-dev libnuma-dev libpopt-dev librtmp-dev
          pip3 install -r transformer/requirements.txt

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run kselftest ${{ matrix.test }}
        run: ./runner.sh ${{ matrix.test }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: kselftest-results-${{ matrix.test }}
          path: |
            ${{ github.workspace }}/parser/results.json

      - name: Parse log files
        run: ./runner.sh -p ${{ matrix.test }}
