name: Run kselftest subsystem tests

on:
  push:
    branches:
      - master
    paths:
      - "api/**"
      - "transformer/**"
      - "parser/**"
      - ".github/workflows/**"
      - "runner.sh"

jobs:
  kselftest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          [
            vm,
            tmpfs,
            capabilities,
            exec,
            clone3,
            membarrier,
            timers,
            filesystem,
          ]

    steps:
      - uses: actions/checkout@v4
      
      # Cache apt packages
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/kselftest.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Prepare the system
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update

      - name: Install all dependencies
        run: |
          sudo apt-get install -y libelf-dev libmnl-dev bison flex libhugetlbfs-dev coccinelle python3 python3-pip \
                                  libaio-dev libcap-dev libcap-ng-dev libelf-dev libfuse-dev libgcc-s1 libhugetlbfs-dev \
                                  libmnl-dev libmount-dev libnuma-dev libpopt-dev librtmp-dev

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip3 install -r transformer/requirements.txt

      - name: Run kselftest ${{ matrix.test }}
        run: ./runner.sh ${{ matrix.test }}

      - name: Parse log files
        run: ./runner.sh -p ${{ matrix.test }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: kselftest-results-${{ matrix.test }}
          path: |
            ${{ github.workspace }}/parser/results.json
