name: Run kselftest subsystem tests

on:
  push:
    branches:
      - master
    paths:
      - "api/**"
      - "transformer/**"
      - "parser/**"
      - ".github/workflows/**"
      - "runner.sh"

jobs:
  kselftest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [vm, tmpfs]

    steps:
      - uses: actions/checkout@latest

      - name: Install all dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev libmnl-dev bison flex coccinelle python3 python3-pip
          pip3 install -r transformer/requirements.txt

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run kselftest ${{ matrix.test }}
        run: ./runner.sh ${{ matrix.test }}
